### PR TITLE
Check for empty line before control structure for better code readability

### PR DESCRIPTION
**Pull request by kernio**
To make code looks better I create this code sniff.
It control that we have a blank line before control structure (if, for, foreach, while, do, switch).

### CODE REVIEW

**Comment by lstrojny** [comment]
Do we want to do this for return statements as well?

**Comment by kernio** [comment]
We can use SF2 code sniff BlankLineBeforeReturnSniff (https://github.com/leaphub/phpcs-symfony2-standard/blob/master/Sniffs/Formatting/BlankLineBeforeReturnSniff.php) or just add there 'T_RETURN'

**Comment by lstrojny** [comment]
Whatever you prefer :)

**Comment by lstrojny** [comment]
Can you add the sniff to the ruleset.xml as well?

**Pull request merged**
